[[redirects]]
  from = "https://youtubeplayclone.netlify.app/api/youtube*"
  to = "https://youtube.googleapis.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://youtubeplayclone.netlify.app/api/suggestions/*"
  to = "https://suggestqueries.google.com/:splat"
  status = 200
  force = true