[[redirects]]
  from = "https://youtubeplayclone.netlify.app/api/youtube*"
  to = "https://youtube.googleapis.com/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*", 
    Access-Control-Allow-Methods = "GET, OPTIONS",
    Access-Control-Allow-Headers = "Content-Type, Authorization" 
  }

[[redirects]]
  from = "https://youtubeplayclone.netlify.app/api/suggestions/*"
  to = "https://suggestqueries.google.com/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Content-Security-Policy = "default-src 'self' https://youtube.googleapis.com"